sudo: required
services:
  - docker

env:
  global:
  - DOCKER_USER="grrrck"
  - secure: "XsXSJnsJLWSSOms4KSefckuovDT/OaEq1u6JzZtu3nKrYHFaf4ATRGBKmQHC0s2NTe/Yu2KYYucbxzhIsjl1yXZYIbmH3eGG4PlZGmTOczV5a2QMD6hykSezq+LMcEMtVpld6oDKXzBdRO+OyloKpaVx+7taKO0l5QU4SqW2CkmbJSk++dneO/gIlIBgYzj/Judu6Ar0tiLylsIZQ7Q4g5n8u2Gq2iHrWhQqcvhoLONjFhwEQxA+sWNsnwN0Ng8Xk1zIwy0nfTfeKTtOqGBYDBCEQz38WdXr3yoAOWm3gVnAf44+evWlQ1am1xIhwoCy/kR47yGt0wUuNI2yHrzdl58CXPPm/KWVWwVzlomiJMidSMGwpMX4167jrUJpF67zbbO3Pw3HjIeAFjZ2+DfBlPji5aQ+5UowICZUkwDij0olduDvBhrJUPnno047jyW2Y68muiAiGLYZUFwuyNIwucL1uE8GPPp4QnAYJRYBH4ppxagqQi62HNx1biFh3euYNbogg7q/WS21TmWLO5zgaZ2hA7NPai05S5u3rkrtCKutMQ0oZM1m3RYBZGt8RIxWFlDoxSc1aJ493KxQ2tGQeEHn+69dR7CpNxh42/qx13En0OWVSFTSvakblCPG+NLE/Nd+pp5yeu0EuQXiZfhkGtQGQX+5fUdCJQDPItbgQUw="
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO="rstudio-keras"

script:
  - docker build -f Dockerfile -t $DOCKER_USER/$REPO:$COMMIT .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $DOCKER_USER/$REPO:$COMMIT $DOCKER_USER/$REPO:latest;
    docker tag $DOCKER_USER/$REPO:$COMMIT $DOCKER_USER/$REPO:travis-$TRAVIS_BUILD_NUMBER;
    docker push $DOCKER_USER/$REPO;
    fi

