sudo: required
services:
  - docker

env:
  global:
  - secure: Rk3/b9lC8mcfNe4ZWHzid5DUCx1Ynui5fjooT2hv4UA3NQOk3XAGwkYtk4RZnYR/ceGrHqJjkrw5ugh72lwYv/CZOFIyZH1ctcFwKB4NENmb3fMQeMil6ArWIA7PwlJNtT6SkUTi8iqWDviGF/MjxNHwzLPKZJo3I74Fq3PAaA58vdHFVtiquP3T6IxdCvUwvYtYqSb5OH2/8Dmdohnael3J2clhipYJtxLOHcCdpRlbNlUZHqV92z0V09ZbxYpPMVmUhI2Jc2EpuZZifXIt2Xusv2kJBKHG0rZkWBt8q9ywkFW5d+ZulZy75Qgwx65uV8+pBZNRajGM1Diwt5Q3vxpu9KgWa2Ar0fmqe5HDv70J0j3dSohxy8AgQJJoKjWnFFqf3mMj6rFGt+ieG25Lr/D19XskXJFj6hysmQ05xy6B2ASwB1ioFIcNfTrpOmLPxzwTUC6cNvK5vs7WocoqYmNHNijj8pyuF1WKUI8L8gDv303yt5GE60TLYceS+1dMvbmRJzV4ofomyygJ48YmZKv8AomvXUmwH+6Ten79ALpqVYsyE7safw07zWPHyPRG8vekJJbbDaaWhqQUKA+IfzlgvXi5adSFNOq4eSik0wQJzIYoGKtSVpm8ZOZThH1JdgcfmvXjCGyL2B1eaD/Ej7hOtHig/fHg1bsk1Xassa0=
  - secure: "ITUMbdsvUL8/0jRd6dnymNtXRUPTO9WhVEbSW0sMm6YAY19XjdZJqn9yY3Onsp6y4Y7Bi/XtByLXyEMoBJ7/M8YqGm1pzZyguDFE/J709JZ2iIWribXsdsVsHaU6msMEp/thz+U8IqKpBeeHK2NlI78nsXdliYpifGgLOXLsTPyWC0wX2Kj+qvy3CokyELPlwIMbDEOHZCgwriCtW0bCrNPvjnl2tY5KrncwyncP04LD2dZ/CbOWe52X8shhYSOVP1PMYg/HKIspo6oaEq7viQ0BCKAn9hB0M/tLzr7YMoGk+ynMd6nbpsg6YvutampE1TKWqd+QAimsRt5ylsagx9YC2NS7KFJH7fzVC7qj68HHIUVYzNL1FnodHElbrcZkCWlSTPmijpzy55PC7K8FEZho55THaRD2W+uMOwa/jpJyN1bSzZ9oSXE4yidmikoVomftJ4H/zz+k3BRLYQSPbOhpU0ow8en/z3Cp1Br1/cEsFYOgC9tMCVZ5K0VRNJrZ+tS2v+VVNz42EtdTKPGi09r4UlpLZkCa2lOesNj2fEbuGKffQV0JClF/vK44yC69oIMS8cbNIrJDsfYwFmt4xRyGZ3PnVbZfAw9Nnao96SNZcxEGU3yTb/ZcPlG0DClQ/4vmGg6Eh5mZ31TaLrLIf4G/fyzQcNi/OLPqMcdFbp4="
  - secure: "XsXSJnsJLWSSOms4KSefckuovDT/OaEq1u6JzZtu3nKrYHFaf4ATRGBKmQHC0s2NTe/Yu2KYYucbxzhIsjl1yXZYIbmH3eGG4PlZGmTOczV5a2QMD6hykSezq+LMcEMtVpld6oDKXzBdRO+OyloKpaVx+7taKO0l5QU4SqW2CkmbJSk++dneO/gIlIBgYzj/Judu6Ar0tiLylsIZQ7Q4g5n8u2Gq2iHrWhQqcvhoLONjFhwEQxA+sWNsnwN0Ng8Xk1zIwy0nfTfeKTtOqGBYDBCEQz38WdXr3yoAOWm3gVnAf44+evWlQ1am1xIhwoCy/kR47yGt0wUuNI2yHrzdl58CXPPm/KWVWwVzlomiJMidSMGwpMX4167jrUJpF67zbbO3Pw3HjIeAFjZ2+DfBlPji5aQ+5UowICZUkwDij0olduDvBhrJUPnno047jyW2Y68muiAiGLYZUFwuyNIwucL1uE8GPPp4QnAYJRYBH4ppxagqQi62HNx1biFh3euYNbogg7q/WS21TmWLO5zgaZ2hA7NPai05S5u3rkrtCKutMQ0oZM1m3RYBZGt8RIxWFlDoxSc1aJ493KxQ2tGQeEHn+69dR7CpNxh42/qx13En0OWVSFTSvakblCPG+NLE/Nd+pp5yeu0EuQXiZfhkGtQGQX+5fUdCJQDPItbgQUw="
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO="rstudio-keras"

script:
  - docker build -f Dockerfile -t $DOCKER_USER/$REPO:$COMMIT .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $DOCKER_USER/$REPO:$COMMIT $DOCKER_USER/$REPO:latest;
    docker tag $DOCKER_USER/$REPO:$COMMIT $DOCKER_USER/$REPO:travis-$TRAVIS_BUILD_NUMBER;
    docker push $DOCKER_USER/$REPO;
    fi

